// Get online players and some information about them
//@no-log
//GET http://playteawbeta.apexmc.co:1850/api/online_players
GET localhost:1850/api/online_players
###

// Towny information
//@no-log
//GET  http://playteawbeta.apexmc.co:1850/api/towny
GET localhost:1850/api/towny
###

// Full player statistics (player must be online)
//@no-log
//GET http://playteawbeta.apexmc.co:1850/api/full_player_stats/1b410ff4-8ca2-4be1-8a97-b9b3bc9e8907
GET localhost:1850/api/full_player_stats/75418e9c-34ef-4926-af64-96d98d10954c
###

// Server info
//@no-log
//GET http://playteawbeta.apexmc.co:1850/api/server_info
GET localhost:1850/api/server_info
###

// Chat history with time option
//@no-log
//GET http://playteawbeta.apexmc.co:1850/api/chat_history?time=1700000000
GET localhost:1850/api/chat_history?time=1700000000
###

// PvP log
//@no-log
GET http://localhost:1850/api/kill_history
###

// Offline player stats (only returns stats under the general category)
//@no-log
//GET localhost:1850/api/offline_player_stats/75418e9c-34ef-4926-af64-96d98d10954c
// Disabled due to timeout bug

